[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pyphreeqc"
version = "0.0.1"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "numpy",
    "pytest>=6",
]